
//flash.astext.asengine FTE 提供对文本度量、格式和双向文本的复杂控制的低级别支持。尽管可以使用 FTE 创建和管理简单的文本元素，但设计 FTE 的主要目的在于为开发人员创建文本处理组件提供基础。  

include "TextJustifier.as"
include "BreakOpportunity.as"
include "CFFHinting.as"
include "ContentElement.as"
include "DigitCase.as"
include "DigitWidth.as"
include "EastAsianJustifier.as"
include "ElementFormat.as"
include "FontDescription.as"
include "FontLookup.as"
include "FontMetrics.as"
include "FontPosture.as"
include "FontWeight.as"
include "GraphicElement.as"
include "GroupElement.as"
include "JustificationStyle.as"
include "Kerning.as"
include "LigatureLevel.as"
include "LineJustification.as"
include "RenderingMode.as"
include "SpaceJustifier.as"
include "TabAlignment.as"
include "TabStop.as"
include "TextBaseline.as"
include "TextBlock.as"
include "TextElement.as"
include "TextLine.as"
include "TextLineCreationResult.as"
include "TextLineMirrorRegion.as"
include "TextLineValidity.as"
include "TextRotation.as"
include "TypographicCase.as"