LOCAL_PATH := $(call my-dir)

#缂�璇�GGBase妯″��
include $(CLEAR_VARS)

LOCAL_ARM_MODE := arm

LOCAL_MODULE := GGBase

LOCAL_CFLAGS += -include "../StdAfxGGlib.h" \
				-D_ARGB_PIXEL_  \
				-fshort-wchar	\
				-fexceptions
				
LOCAL_C_INCLUDES :=  \
					$(JNI_H_INCLUDE)  \
					$(MY_ANDROID_SOURCE)/frameworks/base/include \
					$(MY_ANDROID_SOURCE)/system/core/include \
					$(MY_ANDROID_SOURCE)/external/astl/include \
					$(MY_ANDROID_SOURCE)/hardware/libhardware/include \
					$(LOCAL_PATH)      \
					$(LOCAL_PATH)/../GGlibrary		\
					$../../../include  \
					$../../../include/base  \
					$../../../include/flash  \
					$../../../include/base/android  \
					$../../../Resource/include  \
					$../../../dependency/mad/include  \
					$../../../dependency/zlib \
					$../../../dependency/gif \
					$../../../dependency/giflib      \
					$../../../dependency/gdx2d	\
					$../../../dependency/libjpeg      \
					$../../../dependency/ssl/include \
					$../../../dependency/ssl/include-common \
					$../../../dependency/ssl/include-local \
					$../../../dependency/ssl/include-android \
					$../../../dependency/iconv/include \
					$../../../dependency/freetype/include \
					$../../../dependency/libpng
					
LOCAL_SRC_FILES += ../StdAfxGGlib.cpp \
					 /../../../../src/base/StdAfxGGBase.cpp \
					 
#gif
LOCAL_SRC_FILES	+=  ../../../../dependency/gif/GifLibary.cpp 

#base android
#MY_FILES := $(wildcard $(LOCAL_PATH)/../../../../src/base/android/*.cpp)
#MY_FILES := $(MY_FILES:$(LOCAL_PATH)/%=%)
#LOCAL_SRC_FILES += $(MY_FILES)				
LOCAL_SRC_FILES	+=  /../../../../src/base/android/GGBase.cpp \
					/../../../../src/base/android/BwImageDecode.cpp	\
					/../../../../src/base/android/MultiStringUtil.cpp \
					/../../../../src/base/android/port_impl.cpp \
					/../../../../src/base/android/string_comp.cpp \
					/../../../../src/base/android/XFile.cpp	\
					/../../../../src/base/android/XGraphics.cpp \
					/../../../../src/base/android/XImage.cpp \
					/../../../../src/base/android/XAcc.cpp \
					/../../../../src/base/android/XMutex.cpp \
					/../../../../src/base/android/XNativeSoundMix.cpp \
					/../../../../src/base/android/XSocket.cpp \
					/../../../../src/base/android/XString.cpp \
					/../../../../src/base/android/XSystem.cpp \
					/../../../../src/base/android/XTime.cpp		\
					/../../../../src/base/android/FontBuffer.cpp \
					../../../../src/base/android/XCamera.cpp \
					/../../../../src/base/android/XCameraDevice.cpp \
					/../../../../src/base/android/XWaveIn.cpp \
					/../../../../src/base/android/XMicrophone.cpp \
					/../../../../src/base/SSLAPI.cpp \
					/../../../../src/base/android/WindowView.cpp \
					/../../../../src/base/android/XFontDraw.cpp \
					/../../../../src/base/XCom.cpp


#mad
MY_FILES := $(wildcard $(LOCAL_PATH)/../../../../dependency/mad/src/*.c)
MY_FILES := $(MY_FILES:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES += $(MY_FILES)

#zlib
LOCAL_SRC_FILES +=  /../../../../dependency/zlib/adler32.c \
					/../../../../dependency/zlib/compress.c \
					/../../../../dependency/zlib/crc32.c \
					/../../../../dependency/zlib/deflate.c \
					/../../../../dependency/zlib/gzio.c \
					/../../../../dependency/zlib/infback.c \
					/../../../../dependency/zlib/inffast.c \
					/../../../../dependency/zlib/inflate.c \
					/../../../../dependency/zlib/inftrees.c \
					/../../../../dependency/zlib/trees.c \
					/../../../../dependency/zlib/uncompr.c \
					/../../../../dependency/zlib/zutil.c 
					
#glib
LOCAL_SRC_FILES += /../../../../dependency/gzip/bits.cpp	\
				   /../../../../dependency/gzip/crypt.cpp	\
				   /../../../../src/base/android/GlobalPortingFunction.cpp \
				   /../../../../dependency/gzip/Deflate.cpp	\
				   /../../../../dependency/gzip/gzbuffer.cpp	\
				   /../../../../dependency/gzip/gzip.cpp	\
				   /../../../../dependency/gzip/inflate.cpp	\
				   /../../../../dependency/gzip/lzw.cpp		\
				   /../../../../dependency/gzip/primos.cpp	\
				   /../../../../dependency/gzip/tailor.cpp	\
				   /../../../../dependency/gzip/trees.cpp	\
				   /../../../../dependency/gzip/unlzh.cpp	\
				   /../../../../dependency/gzip/unlzw.cpp	\
				   /../../../../dependency/gzip/unpack.cpp	\
				   /../../../../dependency/gzip/unzip.cpp	\
				   /../../../../dependency/gzip/util.cpp	\
				   /../../../../dependency/gzip/zip.cpp
					
LOCAL_SRC_FILES +=  /../../../../dependency/gdx2d/gdx2d.c \
					/../../../../dependency/gdx2d/StbImage.c \
					
LOCAL_SRC_FILES	+=  /../../../../src/base/XButton.cpp \
					/../../../../src/base/XData.cpp \
					/../../../../src/base/XDialog.cpp \
					/../../../../src/base/XDib.cpp \
					/../../../../src/base/XEdit.cpp \
					/../../../../src/base/XFastAlloc.cpp \
					/../../../../src/base/XHScrollBar.cpp \
					/../../../../src/base/XListBox.cpp \
					/../../../../src/base/XMenu.cpp \
					/../../../../src/base/XMp3Decomp.cpp \
					/../../../../src/base/XResource.cpp \
					/../../../../src/base/XScrollBar.cpp \
					/../../../../src/base/XSort.cpp \
					/../../../../src/base/XStream.cpp \
					/../../../../src/base/XTabControl.cpp \
					/../../../../src/base/XVector.cpp \
					/../../../../src/base/XVScrollBar.cpp \
					/../../../../src/base/XWindow.cpp \
					/../../../../src/base/XZLib.cpp

#7z
LOCAL_SRC_FILES += /../../../../dependency/7z/7zAlloc.c	\
				   /../../../../dependency/7z/7zBuf.c	\
				   /../../../../dependency/7z/7zBuf2.c	\
				   /../../../../dependency/7z/7zCrc.c	\
				   /../../../../dependency/7z/7zCrcOpt.c	\
				   /../../../../dependency/7z/7zDec.c	\
				   /../../../../dependency/7z/7zFile.c	\
				   /../../../../dependency/7z/7zIn.c	\
				   /../../../../dependency/7z/7zStream.c	\
				   /../../../../dependency/7z/7zwrapper.cpp	\
				   /../../../../dependency/7z/Alloc.c	\
				   /../../../../dependency/7z/Bcj2.c	\
				   /../../../../dependency/7z/Bra.c	\
				   /../../../../dependency/7z/Bra86.c	\
				   /../../../../dependency/7z/CpuArch.c	\
				   /../../../../dependency/7z/Delta.c	\
				   /../../../../dependency/7z/LzFind.c	\
				   /../../../../dependency/7z/LzFindMt.c	\
				   /../../../../dependency/7z/Lzma2Dec.c	\
				   /../../../../dependency/7z/Lzma2Enc.c	\
				   /../../../../dependency/7z/Lzma86Dec.c	\
				   /../../../../dependency/7z/Lzma86Enc.c	\
				   /../../../../dependency/7z/LzmaDec.c	\
				   /../../../../dependency/7z/LzmaEnc.c	\
				   /../../../../dependency/7z/LzmaLib.c	\
				   /../../../../dependency/7z/MtCoder.c	\
				   /../../../../dependency/7z/Ppmd7.c	\
				   /../../../../dependency/7z/Ppmd7Dec.c	\
				   /../../../../dependency/7z/Ppmd7Enc.c	\
				   /../../../../dependency/7z/Sha256.c	\
				   /../../../../dependency/7z/Threads.c	\
				   /../../../../dependency/7z/Xz.c	\
				   /../../../../dependency/7z/XzCrc64.c	\
				   /../../../../dependency/7z/XzDec.c	\
				   /../../../../dependency/7z/XzEnc.c	\
				   /../../../../dependency/7z/XzIn.c

				   
#ssl
LOCAL_SRC_FILES += /../../../../dependency/ssl/src/a_bitstr.c \
					/../../../../dependency/ssl/src/a_bool.c \
					/../../../../dependency/ssl/src/a_bytes.c \
					/../../../../dependency/ssl/src/a_d2i_fp.c \
					/../../../../dependency/ssl/src/a_digest.c \
					/../../../../dependency/ssl/src/a_dup.c \
					/../../../../dependency/ssl/src/a_enum.c \
					/../../../../dependency/ssl/src/aes_cbc.c \
					/../../../../dependency/ssl/src/aes_cfb.c \
					/../../../../dependency/ssl/src/aes_core.c \
					/../../../../dependency/ssl/src/aes_ctr.c \
					/../../../../dependency/ssl/src/aes_ecb.c \
					/../../../../dependency/ssl/src/aes_ige.c \
					/../../../../dependency/ssl/src/aes_misc.c \
					/../../../../dependency/ssl/src/aes_ofb.c \
					/../../../../dependency/ssl/src/aes_wrap.c \
					/../../../../dependency/ssl/src/a_gentm.c \
					/../../../../dependency/ssl/src/a_i2d_fp.c \
					/../../../../dependency/ssl/src/a_int.c \
					/../../../../dependency/ssl/src/a_mbstr.c \
					/../../../../dependency/ssl/src/ameth_lib.c \
					/../../../../dependency/ssl/src/a_object.c \
					/../../../../dependency/ssl/src/a_octet.c \
					/../../../../dependency/ssl/src/a_print.c \
					/../../../../dependency/ssl/src/a_set.c \
					/../../../../dependency/ssl/src/a_sign.c \
					/../../../../dependency/ssl/src/asn1_err.c \
					/../../../../dependency/ssl/src/asn1_gen.c \
					/../../../../dependency/ssl/src/asn1_lib.c \
					/../../../../dependency/ssl/src/asn1_par.c \
					/../../../../dependency/ssl/src/asn_mime.c \
					/../../../../dependency/ssl/src/asn_moid.c \
					/../../../../dependency/ssl/src/asn_pack.c \
					/../../../../dependency/ssl/src/a_strex.c \
					/../../../../dependency/ssl/src/a_strnid.c \
					/../../../../dependency/ssl/src/a_time.c \
					/../../../../dependency/ssl/src/a_type.c \
					/../../../../dependency/ssl/src/a_utctm.c \
					/../../../../dependency/ssl/src/a_utf8.c \
					/../../../../dependency/ssl/src/a_verify.c \
					/../../../../dependency/ssl/src/b_dump.c \
					/../../../../dependency/ssl/src/bf_buff.c \
					/../../../../dependency/ssl/src/bf_nbio.c \
					/../../../../dependency/ssl/src/bf_null.c \
					/../../../../dependency/ssl/src/bio_asn1.c \
					/../../../../dependency/ssl/src/bio_b64.c \
					/../../../../dependency/ssl/src/bio_cb.c \
					/../../../../dependency/ssl/src/bio_enc.c \
					/../../../../dependency/ssl/src/bio_err.c \
					/../../../../dependency/ssl/src/bio_lib.c \
					/../../../../dependency/ssl/src/bio_md.c \
					/../../../../dependency/ssl/src/bio_ndef.c \
					/../../../../dependency/ssl/src/bio_ok.c \
					/../../../../dependency/ssl/src/bio_pk7.c \
					/../../../../dependency/ssl/src/bio_ssl.c \
					/../../../../dependency/ssl/src/bn_add.c \
					/../../../../dependency/ssl/src/bn_asm.c \
					/../../../../dependency/ssl/src/bn_blind.c \
					/../../../../dependency/ssl/src/bn_const.c \
					/../../../../dependency/ssl/src/bn_ctx.c \
					/../../../../dependency/ssl/src/bn_depr.c \
					/../../../../dependency/ssl/src/bn_div.c \
					/../../../../dependency/ssl/src/bn_err.c \
					/../../../../dependency/ssl/src/bn_exp2.c \
					/../../../../dependency/ssl/src/bn_exp.c \
					/../../../../dependency/ssl/src/bn_gcd.c \
					/../../../../dependency/ssl/src/bn_gf2m.c \
					/../../../../dependency/ssl/src/bn_kron.c \
					/../../../../dependency/ssl/src/bn_lib.c \
					/../../../../dependency/ssl/src/bn_mod.c \
					/../../../../dependency/ssl/src/bn_mont.c \
					/../../../../dependency/ssl/src/bn_mpi.c \
					/../../../../dependency/ssl/src/bn_mul.c \
					/../../../../dependency/ssl/src/bn_nist.c \
					/../../../../dependency/ssl/src/bn_prime.c \
					/../../../../dependency/ssl/src/bn_print.c \
					/../../../../dependency/ssl/src/bn_rand.c \
					/../../../../dependency/ssl/src/bn_recp.c \
					/../../../../dependency/ssl/src/bn_shift.c \
					/../../../../dependency/ssl/src/bn_sqr.c \
					/../../../../dependency/ssl/src/bn_sqrt.c \
					/../../../../dependency/ssl/src/bn_word.c \
					/../../../../dependency/ssl/src/b_print.c \
					/../../../../dependency/ssl/src/b_sock.c \
					/../../../../dependency/ssl/src/bss_acpt.c \
					/../../../../dependency/ssl/src/bss_bio.c \
					/../../../../dependency/ssl/src/bss_conn.c \
					/../../../../dependency/ssl/src/bss_dgram.c \
					/../../../../dependency/ssl/src/bss_fd.c \
					/../../../../dependency/ssl/src/bss_file.c \
					/../../../../dependency/ssl/src/bss_log.c \
					/../../../../dependency/ssl/src/bss_mem.c \
					/../../../../dependency/ssl/src/bss_null.c \
					/../../../../dependency/ssl/src/bss_sock.c \
					/../../../../dependency/ssl/src/buf_err.c \
					/../../../../dependency/ssl/src/buffer.c \
					/../../../../dependency/ssl/src/by_dir.c \
					/../../../../dependency/ssl/src/by_file.c \
					/../../../../dependency/ssl/src/c_all.c \
					/../../../../dependency/ssl/src/c_allc.c \
					/../../../../dependency/ssl/src/c_alld.c \
					/../../../../dependency/ssl/src/cbc128.c \
					/../../../../dependency/ssl/src/cbc_cksm.c \
					/../../../../dependency/ssl/src/cbc_enc.c \
					/../../../../dependency/ssl/src/cfb128.c \
					/../../../../dependency/ssl/src/cfb64ede.c \
					/../../../../dependency/ssl/src/cfb64enc.c \
					/../../../../dependency/ssl/src/cfb_enc.c \
					/../../../../dependency/ssl/src/conf_api.c \
					/../../../../dependency/ssl/src/conf_def.c \
					/../../../../dependency/ssl/src/conf_err.c \
					/../../../../dependency/ssl/src/conf_lib.c \
					/../../../../dependency/ssl/src/conf_mall.c \
					/../../../../dependency/ssl/src/conf_mod.c \
					/../../../../dependency/ssl/src/conf_sap.c \
					/../../../../dependency/ssl/src/cpt_err.c \
					/../../../../dependency/ssl/src/cryptlib.c \
					/../../../../dependency/ssl/src/ctr128.c \
					/../../../../dependency/ssl/src/cts128.c \
					/../../../../dependency/ssl/src/d1_both.c \
					/../../../../dependency/ssl/src/d1_clnt.c \
					/../../../../dependency/ssl/src/d1_enc.c \
					/../../../../dependency/ssl/src/d1_lib.c \
					/../../../../dependency/ssl/src/d1_meth.c \
					/../../../../dependency/ssl/src/d1_pkt.c \
					/../../../../dependency/ssl/src/d1_srvr.c \
					/../../../../dependency/ssl/src/d2i_pr.c \
					/../../../../dependency/ssl/src/d2i_pu.c \
					/../../../../dependency/ssl/src/des_enc.c \
					/../../../../dependency/ssl/src/des_old2.c \
					/../../../../dependency/ssl/src/des_old.c \
					/../../../../dependency/ssl/src/digest.c \
					/../../../../dependency/ssl/src/dsa_ameth.c \
					/../../../../dependency/ssl/src/dsa_asn1.c \
					/../../../../dependency/ssl/src/dsa_depr.c \
					/../../../../dependency/ssl/src/dsa_err.c \
					/../../../../dependency/ssl/src/dsa_gen.c \
					/../../../../dependency/ssl/src/dsa_key.c \
					/../../../../dependency/ssl/src/dsa_lib.c \
					/../../../../dependency/ssl/src/dsa_ossl.c \
					/../../../../dependency/ssl/src/dsa_pmeth.c \
					/../../../../dependency/ssl/src/dsa_prn.c \
					/../../../../dependency/ssl/src/dsa_sign.c \
					/../../../../dependency/ssl/src/dsa_vrf.c \
					/../../../../dependency/ssl/src/dso_beos.c \
					/../../../../dependency/ssl/src/dso_dl.c \
					/../../../../dependency/ssl/src/dso_dlfcn.c \
					/../../../../dependency/ssl/src/dso_err.c \
					/../../../../dependency/ssl/src/dso_lib.c \
					/../../../../dependency/ssl/src/dso_null.c \
					/../../../../dependency/ssl/src/dso_openssl.c \
					/../../../../dependency/ssl/src/dso_vms.c \
					/../../../../dependency/ssl/src/dso_win32.c \
					/../../../../dependency/ssl/src/e_aes.c \
					/../../../../dependency/ssl/src/ebcdic.c \
					/../../../../dependency/ssl/src/e_bf.c \
					/../../../../dependency/ssl/src/e_camellia.c \
					/../../../../dependency/ssl/src/e_cast.c \
					/../../../../dependency/ssl/src/ecb3_enc.c \
					/../../../../dependency/ssl/src/ecb_enc.c \
					/../../../../dependency/ssl/src/ede_cbcm_enc.c \
					/../../../../dependency/ssl/src/e_des3.c \
					/../../../../dependency/ssl/src/e_des.c \
					/../../../../dependency/ssl/src/e_idea.c \
					/../../../../dependency/ssl/src/encode.c \
					/../../../../dependency/ssl/src/enc_read.c \
					/../../../../dependency/ssl/src/enc_writ.c \
					/../../../../dependency/ssl/src/e_null.c \
					/../../../../dependency/ssl/src/e_old.c \
					/../../../../dependency/ssl/src/e_rc2.c \
					/../../../../dependency/ssl/src/e_rc4.c \
					/../../../../dependency/ssl/src/e_rc5.c \
					/../../../../dependency/ssl/src/err_all.c \
					/../../../../dependency/ssl/src/err.c \
					/../../../../dependency/ssl/src/err_prn.c \
					/../../../../dependency/ssl/src/e_seed.c \
					/../../../../dependency/ssl/src/evp_acnf.c \
					/../../../../dependency/ssl/src/evp_asn1.c \
					/../../../../dependency/ssl/src/evp_enc.c \
					/../../../../dependency/ssl/src/evp_err.c \
					/../../../../dependency/ssl/src/evp_key.c \
					/../../../../dependency/ssl/src/evp_lib.c \
					/../../../../dependency/ssl/src/evp_pbe.c \
					/../../../../dependency/ssl/src/evp_pkey.c \
					/../../../../dependency/ssl/src/e_xcbc_d.c \
					/../../../../dependency/ssl/src/ex_data.c \
					/../../../../dependency/ssl/src/fcrypt_b.c \
					/../../../../dependency/ssl/src/fcrypt.c \
					/../../../../dependency/ssl/src/f_enum.c \
					/../../../../dependency/ssl/src/f_int.c \
					/../../../../dependency/ssl/src/f_string.c \
					/../../../../dependency/ssl/src/hmac.c \
					/../../../../dependency/ssl/src/hm_ameth.c \
					/../../../../dependency/ssl/src/hm_pmeth.c \
					/../../../../dependency/ssl/src/i2d_pr.c \
					/../../../../dependency/ssl/src/i2d_pu.c \
					/../../../../dependency/ssl/src/krb5_asn.c \
					/../../../../dependency/ssl/src/kssl.c \
					/../../../../dependency/ssl/src/lhash.c \
					/../../../../dependency/ssl/src/lh_stats.c \
					/../../../../dependency/ssl/src/md5_dgst.c \
					/../../../../dependency/ssl/src/md5_one.c \
					/../../../../dependency/ssl/src/md_rand.c \
					/../../../../dependency/ssl/src/m_dss1.c \
					/../../../../dependency/ssl/src/m_dss.c \
					/../../../../dependency/ssl/src/m_ecdsa.c \
					/../../../../dependency/ssl/src/mem.c \
					/../../../../dependency/ssl/src/mem_clr.c \
					/../../../../dependency/ssl/src/mem_dbg.c \
					/../../../../dependency/ssl/src/m_md2.c \
					/../../../../dependency/ssl/src/m_md4.c \
					/../../../../dependency/ssl/src/m_md5.c \
					/../../../../dependency/ssl/src/m_mdc2.c \
					/../../../../dependency/ssl/src/m_null.c \
					/../../../../dependency/ssl/src/m_ripemd.c \
					/../../../../dependency/ssl/src/m_sha1.c \
					/../../../../dependency/ssl/src/m_sha.c \
					/../../../../dependency/ssl/src/m_sigver.c \
					/../../../../dependency/ssl/src/m_wp.c \
					/../../../../dependency/ssl/src/names.c \
					/../../../../dependency/ssl/src/n_pkey.c \
					/../../../../dependency/ssl/src/nsseq.c \
					/../../../../dependency/ssl/src/obj_dat.c \
					/../../../../dependency/ssl/src/obj_err.c \
					/../../../../dependency/ssl/src/obj_lib.c \
					/../../../../dependency/ssl/src/obj_xref.c \
					/../../../../dependency/ssl/src/ocsp_asn.c \
					/../../../../dependency/ssl/src/ocsp_cl.c \
					/../../../../dependency/ssl/src/ocsp_err.c \
					/../../../../dependency/ssl/src/ocsp_ext.c \
					/../../../../dependency/ssl/src/ocsp_ht.c \
					/../../../../dependency/ssl/src/ocsp_lib.c \
					/../../../../dependency/ssl/src/ocsp_prn.c \
					/../../../../dependency/ssl/src/ocsp_srv.c \
					/../../../../dependency/ssl/src/ocsp_vfy.c \
					/../../../../dependency/ssl/src/o_dir.c \
					/../../../../dependency/ssl/src/ofb128.c \
					/../../../../dependency/ssl/src/ofb64ede.c \
					/../../../../dependency/ssl/src/ofb64enc.c \
					/../../../../dependency/ssl/src/ofb_enc.c \
					/../../../../dependency/ssl/src/o_names.c \
					/../../../../dependency/ssl/src/o_str.c \
					/../../../../dependency/ssl/src/o_time.c \
					/../../../../dependency/ssl/src/p12_add.c \
					/../../../../dependency/ssl/src/p12_asn.c \
					/../../../../dependency/ssl/src/p12_attr.c \
					/../../../../dependency/ssl/src/p12_crpt.c \
					/../../../../dependency/ssl/src/p12_crt.c \
					/../../../../dependency/ssl/src/p12_decr.c \
					/../../../../dependency/ssl/src/p12_init.c \
					/../../../../dependency/ssl/src/p12_key.c \
					/../../../../dependency/ssl/src/p12_kiss.c \
					/../../../../dependency/ssl/src/p12_mutl.c \
					/../../../../dependency/ssl/src/p12_npas.c \
					/../../../../dependency/ssl/src/p12_p8d.c \
					/../../../../dependency/ssl/src/p12_p8e.c \
					/../../../../dependency/ssl/src/p12_utl.c \
					/../../../../dependency/ssl/src/p5_crpt2.c \
					/../../../../dependency/ssl/src/p5_crpt.c \
					/../../../../dependency/ssl/src/p5_pbe.c \
					/../../../../dependency/ssl/src/p5_pbev2.c \
					/../../../../dependency/ssl/src/p8_pkey.c \
					/../../../../dependency/ssl/src/pcbc_enc.c \
					/../../../../dependency/ssl/src/pcy_cache.c \
					/../../../../dependency/ssl/src/pcy_data.c \
					/../../../../dependency/ssl/src/pcy_lib.c \
					/../../../../dependency/ssl/src/pcy_map.c \
					/../../../../dependency/ssl/src/pcy_node.c \
					/../../../../dependency/ssl/src/pcy_tree.c \
					/../../../../dependency/ssl/src/p_dec.c \
					/../../../../dependency/ssl/src/pem_all.c \
					/../../../../dependency/ssl/src/pem_err.c \
					/../../../../dependency/ssl/src/pem_info.c \
					/../../../../dependency/ssl/src/pem_lib.c \
					/../../../../dependency/ssl/src/pem_oth.c \
					/../../../../dependency/ssl/src/pem_pk8.c \
					/../../../../dependency/ssl/src/pem_pkey.c \
					/../../../../dependency/ssl/src/pem_seal.c \
					/../../../../dependency/ssl/src/pem_sign.c \
					/../../../../dependency/ssl/src/pem_x509.c \
					/../../../../dependency/ssl/src/pem_xaux.c \
					/../../../../dependency/ssl/src/p_enc.c \
					/../../../../dependency/ssl/src/pk12err.c \
					/../../../../dependency/ssl/src/pk7_asn1.c \
					/../../../../dependency/ssl/src/pk7_attr.c \
					/../../../../dependency/ssl/src/pk7_doit.c \
					/../../../../dependency/ssl/src/pk7_lib.c \
					/../../../../dependency/ssl/src/pk7_mime.c \
					/../../../../dependency/ssl/src/pk7_smime.c \
					/../../../../dependency/ssl/src/pkcs7err.c \
					/../../../../dependency/ssl/src/p_lib.c \
					/../../../../dependency/ssl/src/pmeth_fn.c \
					/../../../../dependency/ssl/src/pmeth_gn.c \
					/../../../../dependency/ssl/src/pmeth_lib.c \
					/../../../../dependency/ssl/src/p_open.c \
					/../../../../dependency/ssl/src/pqueue.c \
					/../../../../dependency/ssl/src/p_seal.c \
					/../../../../dependency/ssl/src/p_sign.c \
					/../../../../dependency/ssl/src/p_verify.c \
					/../../../../dependency/ssl/src/pvkfmt.c \
					/../../../../dependency/ssl/src/qud_cksm.c \
					/../../../../dependency/ssl/src/rand_egd.c \
					/../../../../dependency/ssl/src/rand_err.c \
					/../../../../dependency/ssl/src/randfile.c \
					/../../../../dependency/ssl/src/rand_key.c \
					/../../../../dependency/ssl/src/rand_lib.c \
					/../../../../dependency/ssl/src/rand_nw.c \
					/../../../../dependency/ssl/src/rand_os2.c \
					/../../../../dependency/ssl/src/rand_unix.c \
					/../../../../dependency/ssl/src/rand_win.c \
					/../../../../dependency/ssl/src/read2pwd.c \
					/../../../../dependency/ssl/src/rpc_enc.c \
					/../../../../dependency/ssl/src/rsa_ameth.c \
					/../../../../dependency/ssl/src/rsa_asn1.c \
					/../../../../dependency/ssl/src/rsa_chk.c \
					/../../../../dependency/ssl/src/rsa_depr.c \
					/../../../../dependency/ssl/src/rsa_eay.c \
					/../../../../dependency/ssl/src/rsa_err.c \
					/../../../../dependency/ssl/src/rsa_gen.c \
					/../../../../dependency/ssl/src/rsa_lib.c \
					/../../../../dependency/ssl/src/rsa_none.c \
					/../../../../dependency/ssl/src/rsa_null.c \
					/../../../../dependency/ssl/src/rsa_oaep.c \
					/../../../../dependency/ssl/src/rsa_pk1.c \
					/../../../../dependency/ssl/src/rsa_pmeth.c \
					/../../../../dependency/ssl/src/rsa_prn.c \
					/../../../../dependency/ssl/src/rsa_pss.c \
					/../../../../dependency/ssl/src/rsa_saos.c \
					/../../../../dependency/ssl/src/rsa_sign.c \
					/../../../../dependency/ssl/src/rsa_ssl.c \
					/../../../../dependency/ssl/src/rsa_x931.c \
					/../../../../dependency/ssl/src/s23_clnt.c \
					/../../../../dependency/ssl/src/s23_lib.c \
					/../../../../dependency/ssl/src/s23_meth.c \
					/../../../../dependency/ssl/src/s23_pkt.c \
					/../../../../dependency/ssl/src/s23_srvr.c \
					/../../../../dependency/ssl/src/s2_clnt.c \
					/../../../../dependency/ssl/src/s2_enc.c \
					/../../../../dependency/ssl/src/s2_lib.c \
					/../../../../dependency/ssl/src/s2_meth.c \
					/../../../../dependency/ssl/src/s2_pkt.c \
					/../../../../dependency/ssl/src/s2_srvr.c \
					/../../../../dependency/ssl/src/s3_both.c \
					/../../../../dependency/ssl/src/s3_clnt.c \
					/../../../../dependency/ssl/src/s3_enc.c \
					/../../../../dependency/ssl/src/s3_lib.c \
					/../../../../dependency/ssl/src/s3_meth.c \
					/../../../../dependency/ssl/src/s3_pkt.c \
					/../../../../dependency/ssl/src/s3_srvr.c \
					/../../../../dependency/ssl/src/seed.c \
					/../../../../dependency/ssl/src/seed_cbc.c \
					/../../../../dependency/ssl/src/seed_cfb.c \
					/../../../../dependency/ssl/src/seed_ecb.c \
					/../../../../dependency/ssl/src/seed_ofb.c \
					/../../../../dependency/ssl/src/set_key.c \
					/../../../../dependency/ssl/src/sha1dgst.c \
					/../../../../dependency/ssl/src/sha1_one.c \
					/../../../../dependency/ssl/src/sha256.c \
					/../../../../dependency/ssl/src/sha512.c \
					/../../../../dependency/ssl/src/sha_dgst.c \
					/../../../../dependency/ssl/src/sha_one.c \
					/../../../../dependency/ssl/src/ssl_algs.c \
					/../../../../dependency/ssl/src/ssl_asn1.c \
					/../../../../dependency/ssl/src/ssl_cert.c \
					/../../../../dependency/ssl/src/ssl_ciph.c \
					/../../../../dependency/ssl/src/ssl_err2.c \
					/../../../../dependency/ssl/src/ssl_err.c \
					/../../../../dependency/ssl/src/ssl_lib.c \
					/../../../../dependency/ssl/src/ssl_rsa.c \
					/../../../../dependency/ssl/src/ssl_sess.c \
					/../../../../dependency/ssl/src/ssl_stat.c \
					/../../../../dependency/ssl/src/ssl_txt.c \
					/../../../../dependency/ssl/src/stack.c \
					/../../../../dependency/ssl/src/str2key.c \
					/../../../../dependency/ssl/src/t1_clnt.c \
					/../../../../dependency/ssl/src/t1_enc.c \
					/../../../../dependency/ssl/src/t1_lib.c \
					/../../../../dependency/ssl/src/t1_meth.c \
					/../../../../dependency/ssl/src/t1_reneg.c \
					/../../../../dependency/ssl/src/t1_srvr.c \
					/../../../../dependency/ssl/src/tasn_dec.c \
					/../../../../dependency/ssl/src/tasn_enc.c \
					/../../../../dependency/ssl/src/tasn_fre.c \
					/../../../../dependency/ssl/src/tasn_new.c \
					/../../../../dependency/ssl/src/tasn_prn.c \
					/../../../../dependency/ssl/src/tasn_typ.c \
					/../../../../dependency/ssl/src/tasn_utl.c \
					/../../../../dependency/ssl/src/t_bitst.c \
					/../../../../dependency/ssl/src/t_crl.c \
					/../../../../dependency/ssl/src/t_pkey.c \
					/../../../../dependency/ssl/src/t_req.c \
					/../../../../dependency/ssl/src/ts_asn1.c \
					/../../../../dependency/ssl/src/ts_conf.c \
					/../../../../dependency/ssl/src/ts_err.c \
					/../../../../dependency/ssl/src/ts_lib.c \
					/../../../../dependency/ssl/src/t_spki.c \
					/../../../../dependency/ssl/src/ts_req_print.c \
					/../../../../dependency/ssl/src/ts_req_utils.c \
					/../../../../dependency/ssl/src/ts_rsp_print.c \
					/../../../../dependency/ssl/src/ts_rsp_sign.c \
					/../../../../dependency/ssl/src/ts_rsp_utils.c \
					/../../../../dependency/ssl/src/ts_rsp_verify.c \
					/../../../../dependency/ssl/src/ts_verify_ctx.c \
					/../../../../dependency/ssl/src/t_x509a.c \
					/../../../../dependency/ssl/src/t_x509.c \
					/../../../../dependency/ssl/src/txt_db.c \
					/../../../../dependency/ssl/src/ui_compat.c \
					/../../../../dependency/ssl/src/uid.c \
					/../../../../dependency/ssl/src/ui_err.c \
					/../../../../dependency/ssl/src/ui_lib.c \
					/../../../../dependency/ssl/src/ui_openssl.c \
					/../../../../dependency/ssl/src/ui_util.c \
					/../../../../dependency/ssl/src/v3_addr.c \
					/../../../../dependency/ssl/src/v3_akeya.c \
					/../../../../dependency/ssl/src/v3_akey.c \
					/../../../../dependency/ssl/src/v3_alt.c \
					/../../../../dependency/ssl/src/v3_asid.c \
					/../../../../dependency/ssl/src/v3_bcons.c \
					/../../../../dependency/ssl/src/v3_bitst.c \
					/../../../../dependency/ssl/src/v3_conf.c \
					/../../../../dependency/ssl/src/v3_cpols.c \
					/../../../../dependency/ssl/src/v3_crld.c \
					/../../../../dependency/ssl/src/v3_enum.c \
					/../../../../dependency/ssl/src/v3err.c \
					/../../../../dependency/ssl/src/v3_extku.c \
					/../../../../dependency/ssl/src/v3_genn.c \
					/../../../../dependency/ssl/src/v3_ia5.c \
					/../../../../dependency/ssl/src/v3_info.c \
					/../../../../dependency/ssl/src/v3_int.c \
					/../../../../dependency/ssl/src/v3_lib.c \
					/../../../../dependency/ssl/src/v3_ncons.c \
					/../../../../dependency/ssl/src/v3_ocsp.c \
					/../../../../dependency/ssl/src/v3_pcia.c \
					/../../../../dependency/ssl/src/v3_pci.c \
					/../../../../dependency/ssl/src/v3_pcons.c \
					/../../../../dependency/ssl/src/v3_pku.c \
					/../../../../dependency/ssl/src/v3_pmaps.c \
					/../../../../dependency/ssl/src/v3_prn.c \
					/../../../../dependency/ssl/src/v3_purp.c \
					/../../../../dependency/ssl/src/v3_skey.c \
					/../../../../dependency/ssl/src/v3_sxnet.c \
					/../../../../dependency/ssl/src/v3_utl.c \
					/../../../../dependency/ssl/src/wp_block.c \
					/../../../../dependency/ssl/src/wp_dgst.c \
					/../../../../dependency/ssl/src/x509_att.c \
					/../../../../dependency/ssl/src/x509_cmp.c \
					/../../../../dependency/ssl/src/x509cset.c \
					/../../../../dependency/ssl/src/x509_d2.c \
					/../../../../dependency/ssl/src/x509_def.c \
					/../../../../dependency/ssl/src/x509_err.c \
					/../../../../dependency/ssl/src/x509_ext.c \
					/../../../../dependency/ssl/src/x509_lu.c \
					/../../../../dependency/ssl/src/x509name.c \
					/../../../../dependency/ssl/src/x509_obj.c \
					/../../../../dependency/ssl/src/x509_r2x.c \
					/../../../../dependency/ssl/src/x509_req.c \
					/../../../../dependency/ssl/src/x509rset.c \
					/../../../../dependency/ssl/src/x509_set.c \
					/../../../../dependency/ssl/src/x509spki.c \
					/../../../../dependency/ssl/src/x509_trs.c \
					/../../../../dependency/ssl/src/x509_txt.c \
					/../../../../dependency/ssl/src/x509type.c \
					/../../../../dependency/ssl/src/x509_v3.c \
					/../../../../dependency/ssl/src/x509_vfy.c \
					/../../../../dependency/ssl/src/x509_vpm.c \
					/../../../../dependency/ssl/src/x_algor.c \
					/../../../../dependency/ssl/src/x_all.c \
					/../../../../dependency/ssl/src/x_attrib.c \
					/../../../../dependency/ssl/src/x_bignum.c \
					/../../../../dependency/ssl/src/xcbc_enc.c \
					/../../../../dependency/ssl/src/x_crl.c \
					/../../../../dependency/ssl/src/x_exten.c \
					/../../../../dependency/ssl/src/x_info.c \
					/../../../../dependency/ssl/src/x_long.c \
					/../../../../dependency/ssl/src/x_name.c \
					/../../../../dependency/ssl/src/x_nx509.c \
					/../../../../dependency/ssl/src/x_pkey.c \
					/../../../../dependency/ssl/src/x_pubkey.c \
					/../../../../dependency/ssl/src/x_req.c \
					/../../../../dependency/ssl/src/x_sig.c \
					/../../../../dependency/ssl/src/x_spki.c \
					/../../../../dependency/ssl/src/x_val.c \
					/../../../../dependency/ssl/src/x_x509a.c \
					/../../../../dependency/ssl/src/x_x509.c

#LOCAL_LDLIBS := $(MY_LIBRARY)

include $(BUILD_STATIC_LIBRARY)


