#include "XLogEngine.h"


    /** 
     *  log写入器
     *  此log用于记录用户行为
     *  由服务器回收
     *  @author zhangchen
     *  @version 1.0
     */

    /* {deprecated=false}*/




/** 
     *  构造函数
     */
XLogEngine::XLogEngine(char *fname)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A61 begin
{
    m_hFileName = new char[ strlen(fname)+1 ];
    strcpy(m_hFileName, fname);
    m_plRead = m_rMsg;
    m_plWrite = m_rMsg;
    m_bNeedStop = false;
    m_tEvent.ResetEvent();
    m_hThread = new XThread();
    m_hThread->Create(this, 1000);
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/** 
     *  析构函数
     */
XLogEngine::~XLogEngine()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A63 begin
{
    m_tEvent.SetEvent();
    m_hThread->Stop(true);
    while (m_plRead == m_plWrite) {
        delete m_plRead;
        if(m_plRead-m_rMsg>=63)
            m_plRead = m_rMsg;
        else
            m_plRead++;
    }
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A63 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  继承自XBace
     *  查看是否需要停止
     */
XBOOL XLogEngine::NeedStop()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A5C begin
{
    return m_bNeedStop;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A5C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  继承自XBace
     *  线程体
     */
XUINT XLogEngine::CallBack(XU32 nID)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A5E begin
{
    FILE *fl;
    while (true) {
        if (!m_tEvent.IsEvent(10000000))
            continue;
        if (m_hThread->NeedStop())
        {
            if(fl)
                fclose(fl);
            break;
        }
        if(m_plRead == m_plWrite)
        {
            XThread::Sleep(200);
            continue;
        }
        
        char* temp = (*m_plRead)->getString();
        if(fl==NULL)
            fl = fopen(m_hFileName, "a");
        if(fl)
        {
            fprintf(fl, "%s\r\n",temp);
            fflush(fl);
        }
        delete temp;
        if(m_plRead-m_rMsg>=63)
            m_plRead = m_rMsg;
        else
            m_plRead++;
        if(m_plRead==m_plWrite)
        {
            fclose(fl);
            m_tEvent.ResetEvent();
        }
        
    }
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  写入log
     */
void XLogEngine::WriteLog(ZKey *value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A66 begin
{
//    m_plWrite-m_plRead == 63;
//    m_plWrite-m_plRead == -1;
    if(m_plWrite-m_plRead == 63 || m_plWrite-m_plRead == -1)
    {
        delete value;
        return;
    }
    (*m_plWrite) = value;
    if(m_plWrite-m_rMsg == 63)
        m_plWrite = m_rMsg;
    else 
        m_plWrite++;
    m_tEvent.SetEvent();
    return;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A66 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
