#include "ZKey.h"


    /** 
     *  log键值
     *  @author zhangchen
     *  @version 1.0
     */

static char* typeV[]= {
    "start:",
    "end:",
    "gravity:",
    "flashStart:",
    "flashEnd:",
    "changedBar:",
    "memWarning:",
    "wgtPosition:",
    "buttonClick:",
    "time:",
    "angle:",
    "content:",
    "from:",
    "to:",
    "position:",
    "buttonId:",
    "times:"
};

int getVelueLen(int value)
{
    int len(0);
    do{
        value/=10;
        len+=1;
    }while(value);
    return len;
}

ZKey* getTimeKey()
{
    
}

	 
ZKey::ZKey()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A9A begin
{
    m_nValueType = EInt;
    m_nNValue = 0;
    myELogType = EStart;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A9A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


ZKey::ZKey(ELogType name, int value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A9D begin
{
    myELogType = name;
    m_nValueType = EInt;
    m_nNValue = value;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000A9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ZKey::ZKey(ELogType name, char *value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AB7 begin
{
    myELogType = name;
    m_nValueType = EString;
    m_hSValue = new char[ strlen(value) ];
    strcpy(m_hSValue, value);
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AB7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ZKey::ZKey(ELogType name, ZKeyArray *value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AC1 begin
{
    myELogType = name;
    m_nValueType = ETeam;
    m_hAValue = new ZKeyArray(*value);
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AC1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ZKey::~ZKey()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000C1A begin
{
    if(m_nValueType == EString)
        delete m_hSValue;
    if(m_nValueType == ETeam)
        delete m_hAValue;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000C1A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  整理为字符串
     */
char* ZKey::getString()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000ACA begin
{
    char *str = NULL;
    switch (m_nValueType) {
        case EInt:
        {
            int len = strlen(typeV[myELogType]);
            len+=getVelueLen(m_nNValue);
            str = new char[len+3];
            sprintf(str, "%s\"%d\"",typeV[myELogType],m_nNValue);
        }
            break;
        case EString:
        {
            int len = strlen(typeV[myELogType]);
            len+=strlen(m_hSValue);
            str = new char[len+3];
            sprintf(str, "%s\"%s\"",typeV[myELogType],m_hSValue);
        }
            break;
        case ETeam:
        {
            int len = strlen(typeV[myELogType]);
            char *temp = m_hAValue->getString();
            len += strlen(temp);
            str = new char[len+3];
            sprintf(str, "%s{%s}",typeV[myELogType],temp);
            delete temp;
        }
            break;
        default:
            break;
    }
    return str;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000ACA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ZKey ZKey::operator=(ZKey value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AD7 begin
{
    if(m_nValueType == EString)
        delete m_hSValue;
    if(m_nValueType == ETeam)
        delete m_hAValue;
    myELogType = value.myELogType;
    m_nValueType = value.m_nValueType;
    switch (m_nValueType) {
        case EInt:
            m_nNValue = value.m_nNValue;
            break;
        case EString:
            m_hSValue = new char[strlen(value.m_hSValue)];
            strcpy(m_hSValue, value.m_hSValue);
            break;
        case ETeam:
            m_hAValue = new ZKeyArray(*value.m_hAValue);
            break;
        default:
            break;
    }
    return *this;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AD7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
