#include "ZKeyArray.h"
#include "ZKey.h"


    /** 
     *  log键值序列
     *  @author zhangchen
     *  @version 1.0
     */


ZKeyArray::ZKeyArray()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000B25 begin
{
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000B25 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ZKeyArray::ZKeyArray(const ZKeyArray& array)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000B2D begin
:m_tZKey(array.m_tZKey)
{
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000B2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

ZKeyArray::~ZKeyArray()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000BC5 begin
{
    int count = m_tZKey.GetSize();
    if(count>0)
    {
        for(int i=0 ; i<count ; i++)
        {
            delete m_tZKey.GetAt(i);
        }
    }
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000BC5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  添加log键值
     */
bool ZKeyArray::addKey(ZKey *element)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000ACD begin
{
    m_tZKey.Add(element);
    return true;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000ACD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char* ZKeyArray::getString()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AE4 begin
{
    char* str = NULL;
    int strsize(0);
    int count = m_tZKey.GetSize();

    for(int i=0 ; i<count ; i++)
    {
        ZKey* key = m_tZKey.GetAt(i);
        char* temp = key->getString();
        int len = strlen(temp);
        strsize+=len;
        char *temps = new char[strsize+count];
        if(str)
        {
            strcpy(temps, str);
            strcat(temps, ",");
        }
        strcat(temps, temp);
        delete str;
        delete temp;
        str = temps;
    }
    return str;
}
// section -64--88-1-66--7a6b6401:137c55bfd04:-8000:0000000000000AE4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
