//支持的字符集   
//Flash Player 支持一组由 IANA (http://www.iana.org/assignments/character-sets) 指定的样式字符集定义。下表列出了受支持的字符集，您可以使用标签值或别名值（指向同一个基本定义的别名）来指定所需的字符集：
#ifndef _CHAR_SET_H_
#define _CHAR_SET_H_

enum char_set
{
	ASMO_708,
	DOS_720,
	iso_8859_6,
	x_mac_arabic,
	windows_1256,
	ibm775,
	iso_8859_4,
	windows_1257,
	ibm852,
	iso_8859_2,
	x_mac_ce,
	windows_1250,
	EUC_CN,
	gb2312,
	hz_gb_2312,
	x_mac_chinesesimp,
	big5,
	x_Chinese_CNS,
	x_Chinese_Eten,
	x_mac_chinesetrad,
	cp866,
	iso_8859_5,
	koi8_r,
	koi8_u,
	x_mac_cyrillic,
	windows_1251,
	x_Europa,
	x_IA5_German,
	ibm737,
	iso_8859_7,
	x_mac_greek,
	windows_1253,
	ibm869,
	DOS_862,
	iso_8859_8_i,
	iso_8859_8,
	x_mac_hebrew,
	windows_1255,
	x_EBCDIC_Arabic,
	x_EBCDIC_CyrillicRussian,
	x_EBCDIC_CyrillicSerbianBulgarian,
	x_EBCDIC_DenmarkNorway,
	x_ebcdic_denmarknorway_euro,
	x_EBCDIC_FinlandSweden,
	x_ebcdic_finlandsweden_euro,
	x_ebcdic_france_euro,
	x_EBCDIC_Germany,
	x_ebcdic_germany_euro,
	x_EBCDIC_GreekModern,
	x_EBCDIC_Greek,
	x_EBCDIC_Hebrew,
	x_EBCDIC_Icelandic,
	x_ebcdic_icelandic_euro,
	x_ebcdic_international_euro,
	x_EBCDIC_Italy,
	x_ebcdic_italy_euro,
	x_EBCDIC_JapaneseAndKana,
	x_EBCDIC_JapaneseAndJapaneseLatin,
	x_EBCDIC_JapaneseAndUSCanada,
	x_EBCDIC_JapaneseKatakana,
	x_EBCDIC_KoreanAndKoreanExtended,
	x_EBCDIC_KoreanExtended,
	CP870,
	x_EBCDIC_SimplifiedChinese,
	X_EBCDIC_Spain,
	x_ebcdic_spain_euro,
	x_EBCDIC_Thai,
	x_EBCDIC_TraditionalChinese,
	CP1026,
	x_EBCDIC_Turkish,
	x_EBCDIC_UK,
	x_ebcdic_uk_euro,
	ebcdic_cp_us,
	x_ebcdic_cp_us_euro,
	ibm861,
	x_mac_icelandic,
	x_iscii_as,
	x_iscii_BE,
	x_iscii_de,
	x_iscii_gu,
	x_iscii_ka,
	x_iscii_ma,
	x_iscii_OR,
	x_iscii_pa,
	x_iscii_ta,
	x_iscii_te,
	euc_JP,
	iso_2022_JP,
	csISO2022JP,
	x_mac_japanese,
	shift_jis,
	ks_c_5601_1987,
	euc_kr,
	iso_2022_kr,
	Johab,
	x_mac_korean,
	iso_8859_3,
	iso_8859_15,
	x_IA5_Norwegian,
	IBM437,
	x_IA5_Swedish,
	windows_874,
	ibm857,
	iso_8859_9,
	x_mac_turkish,
	windows_1254,
	unicode,
	unicodeFFFE,	//(Big-Endian)
	utf_7,
	utf_8,
	us_ascii,
	windows_1258,
	ibm850,
	x_IA5,
	iso_8859_1,
	macintosh,
	Windows_1252
};
//2004-2007 Adobe Systems Incorporated. All rights reserved. 
//Wed Jun 13 2007, 4:16 AM GMT-07:00 

//const char *g_pc_charSet[] = 
//{
//	"ASMO-708",
//	"DOS-720",
//	"iso-8859-6",
//	"x-mac-arabic",
//	"windows-1256",
//	"ibm775",
//	"iso-8859-4",
//	"windows-1257",
//	"ibm852",
//	"iso-8859-2",
//	"x-mac-ce",
//	"windows-1250",
//	"EUC-CN",
//	"gb2312",
//	"hz-gb-2312",
//	"x-mac-chinesesimp",
//	"big5",
//	"x-Chinese-CNS",
//	"x-Chinese-Eten",
//	"x-mac-chinesetrad",
//	"cp866",
//	"iso-8859-5",
//	"koi8-r",
//	"koi8-u",
//	"x-mac-cyrillic",
//	"windows-1251",
//	"x-Europa",
//	"x-IA5-German",
//	"ibm737",
//	"iso-8859-7",
//	"x-mac-greek",
//	"windows-1253",
//	"ibm869",
//	"DOS-862",
//	"iso-8859-8-i",
//	"iso-8859-8",
//	"x-mac-hebrew",
//	"windows-1255",
//	"x-EBCDIC-Arabic",
//	"x-EBCDIC-CyrillicRussian",
//	"x-EBCDIC-CyrillicSerbianBulgarian",
//	"x-EBCDIC-DenmarkNorway",
//	"x-ebcdic-denmarknorway-euro",
//	"x-EBCDIC-FinlandSweden",
//	"x-ebcdic-finlandsweden-euro",
//	"x-ebcdic-finlandsweden-euro",
//	"x-ebcdic-france-euro",
//	"x-EBCDIC-Germany",
//	"x-ebcdic-germany-euro",
//	"x-EBCDIC-GreekModern",
//	"x-EBCDIC-Greek",
//	"x-EBCDIC-Hebrew",
//	"x-EBCDIC-Icelandic",
//	"x-ebcdic-icelandic-euro",
//	"x-ebcdic-international-euro",
//	"x-EBCDIC-Italy",
//	"x-ebcdic-italy-euro",
//	"x-EBCDIC-JapaneseAndKana",
//	"x-EBCDIC-JapaneseAndJapaneseLatin",
//	"x-EBCDIC-JapaneseAndUSCanada",
//	"x-EBCDIC-JapaneseKatakana",
//	"x-EBCDIC-KoreanAndKoreanExtended",
//	"x-EBCDIC-KoreanExtended",
//	"CP870",
//	"x-EBCDIC-SimplifiedChinese",
//	"X-EBCDIC-Spain",
//	"x-ebcdic-spain-euro",
//	"x-EBCDIC-Thai",
//	"x-EBCDIC-TraditionalChinese",
//	"CP1026",
//	"x-EBCDIC-Turkish",
//	"x-EBCDIC-UK",
//	"x-ebcdic-uk-euro",
//	"ebcdic-cp-us",
//	"x-ebcdic-cp-us-euro",
//	"ibm861",
//	"x-mac-icelandic",
//	"x-iscii-as",
//	"x-iscii-BE",
//	"x-iscii-de",
//	"x-iscii-gu",
//	"x-iscii-ka",
//	"x-iscii-ma",
//	"x-iscii-OR",
//	"x-iscii-pa",
//	"x-iscii-ta",
//	"x-iscii-te",
//	"euc-JP",
//	"iso-2022-JP",
//	"iso-2022-JP",
//	"csISO2022JP",
//	"x-mac-japanese",
//	"shift_jis",
//	"ks_c_5601-1987",
//	"euc-kr",
//	"iso-2022-kr",
//	"Johab",
//	"x-mac-korean",
//	"iso-8859-3",
//	"iso-8859-15",
//	"x-IA5-Norwegian",
//	"IBM437",
//	"x-IA5-Swedish",
//	"windows-874",
//	"ibm857",
//	"iso-8859-9",
//	"x-mac-turkish",
//	"windows-1254",
//	"unicode",
//	"unicodeFFFE",  //(Big-Endian)
//	"utf-7",
//	"utf-8",
//	"us-ascii",
//	"windows-1258",
//	"ibm850",
//	"x-IA5",
//	"iso-8859-1",
//	"macintosh",
//	"Windows-1252"
//}

#endif


 



 