//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GGClient.rc
//
#define IDOK2                           2
#define IDC_DEFAULT                     3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GGCLIENT_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_SETUP                       104
#define IDR_MAINFRAME                   128
#define IDR_SYSTEM                      133
#define IDC_HANDPT                      134
#define IDD_DOMTREE                     156
#define IDB_DOMLIST                     157
#define IDC_HANDON                      166
#define IDC_HIDE                        167
#define IDD_ANALYDLG                    188
#define IDB_STATUS                      189
#define IDR_ANABAR                      191
#define IDB_OBJS                        193
#define IDC_THUMB                       197
#define IDD_TRACE                       200
#define IDD_TEXTEDIT                    202
#define IDD_PLAYERLIST                  209
#define IDD_CAMERA                      210
#define IDD_ACC                         211
#define IDD_DIBINFO                     212
#define IDD_MEMINFO                     213
#define IDD_FLASHBAR                    214
#define IDD_WEBDIALOG                   215
#define IDD_DATAPROC                    218
#define IDC_USERAGENT                   1003
#define IDC_ACCEPTS                     1004
#define IDC_MOBILELIST                  1005
#define IDC_PROFILE                     1006
#define IDC_HTTP                        1007
#define IDC_UDP                         1008
#define IDC_PORT                        1009
#define IDC_GATEWAY                     1010
#define IDC_PROFILE2                    1011
#define IDC_CHANNELID                   1011
#define IDC_TIMEOUT                     1012
#define IDC_RETRIES                     1013
#define IDC_BKCOLOR                     1014
#define IDC_CLIENTID                    1015
#define IDC_TEXTCOLOR                   1016
#define IDC_TREE                        1016
#define IDC_LINKTEXT                    1017
#define IDC_HIBACK                      1018
#define IDC_HITEXT                      1019
#define IDC_ACTIVETEXT                  1020
#define IDC_DEL                         1021
#define IDC_PROFILE3                    1021
#define IDC_MOBILETYPE                  1021
#define IDC_TIMESPIN                    1022
#define IDC_RETRYSPIN                   1023
#define IDC_ADD                         1024
#define IDC_BUTTON                      1025
#define IDC_LIST1                       1029
#define IDC_OBJTREE                     1032
#define IDC_OUTPUT                      1033
#define IDC_ENU                         1034
#define IDC_ENUACC                      1035
#define IDC_GRAPH                       1036
#define IDC_CLEAR                       1039
#define IDC_ENABLEOUT                   1040
#define IDC_FINDTEXT                    1041
#define IDC_BUTTON1                     1042
#define IDC_FIND                        1042
#define IDC_INFOMATION                  1042
#define IDC_BROWNS                      1042
#define IDC_REPLACE                     1042
#define IDC_CAMERA                      1042
#define IDC_SHOW                        1042
#define IDC_PREV                        1042
#define IDC_RESET                       1042
#define IDC_TEXT                        1043
#define IDC_FILELIST                    1044
#define IDC_SAVEC                       1045
#define IDC_SAVE                        1046
#define IDC_SOURCE                      1047
#define IDC_QUIT                        1047
#define IDC_DOUBLE                      1048
#define IDC_SCORE                       1048
#define IDC_INFO                        1049
#define IDC_PAY                         1049
#define IDC_SRCBIN                      1050
#define IDC_ZOOMIN                      1050
#define IDC_DSTBIN                      1051
#define IDC_ZOOMOUT                     1051
#define IDC_RESTART                     1052
#define IDC_LIST                        1053
#define IDC_ROTATE                      1053
#define IDC_LAST                        1054
#define IDC_NEXT                        1055
#define IDD_RESET                       1055
#define IDC_ZOOMBAR                     1058
#define IDC_DEST                        1059
#define IDC_SEARCH                      1060
#define IDC_RADIO1                      1060
#define IDC_STRING                      1061
#define IDC_RADIO2                      1061
#define IDC_INT                         1062
#define IDC_RADIO3                      1062
#define IDC_WEBCNT                      1062
#define IDC_HEX                         1063
#define IDC_PROC                        1063
#define IDC_TOTALFRAME                  1064
#define IDC_TOTALTEXTURES               1065
#define IDC_TOTALIMAGE                  1066
#define IDC_TOTALIMAGE2                 1067
#define IDC_TOTALBUFFER                 1067
#define IDC_DRVLIST                     1104
#define IDC_PATHNAME                    1105
#define IDC_DIRTREE                     1106
#define ID_APP_SOURCE                   32771
#define ID_APP_CONFIG                   32773
#define ID_APP_URL                      32776
#define ID_APP_TREE                     32777
#define ID_APP_DEBUG                    32778
#define ID_APP_MODE                     32780
#define ID_APP_FINDVAR                  32781
#define ID_APP_ANALY                    32782
#define IDA_FUNCTION                    32784
#define IDA_CALLGRAPH                   32785
#define IDA_OBJECTS                     32786
#define IDA_START                       32787
#define IDA_STOP                        32788
#define IDA_CLEAR                       32789
#define IDA_UPDATE                      32790
#define IDA_DISABLE                     32791
#define IDA_ENBLE                       32792
#define IDA_DISABLE_ALL                 32793
#define IDA_GRAPH                       32795
#define ID_32796                        32796
#define ID_APP_OUTPUT                   32797
#define ID_32798                        32798
#define IDA_SHOWMEMBER                  32799
#define IDA_SEARCH                      32800
#define ID_BUTTON32801                  32801
#define ID_SEARCH_TEXT                  32801
#define ID_32802                        32802
#define ID_BINARY                       32803
#define ID_32804                        32804
#define ID_ACC                          32805
#define IDA_BITMAP_SAVE                 32806
#define ID_32807                        32807
#define ID_APP_DIBINFO                  32808
#define ID_32809                        32809
#define ID_APP_MEMINFO                  32810
#define IDS_MEMORY                      57345

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
