	
//flash.asdesktop flash.asdesktop"

include "IFilePromise.as"
include "Clipboard.as"
include "ClipboardFormats.as"
include "ClipboardTransferMode.as"
include "Icon.as"
include "InteractiveIcon.as"
include "DockIcon.as"
include "InvokeEventReason.as"
include "NativeApplication.as"
include "NativeDragActions.as"
include "NativeDragManager.as"
include "NativeDragOptions.as"
include "NativeProcess.as"
include "NativeProcessStartupInfo.as"
include "NotificationType.as"
include "SystemIdleMode.as"
include "SystemTrayIcon.as"
include "Updater.as"
include	"Loader.as"	
