//flash.asdisplay

//include "IGraphicsData.as"	AIR
//include "IGraphicsFill.as"	AIR
//include "IGraphicsPath.as"	AIR
//include "IGraphicsStroke.as"	AIR
//include "ColorCorrection.as"		AIR中已有实现
//include "ColorCorrectionSupport.as"		同上
include	"DisplayObject.as"	
include "FocusDirection.as"
include "GraphicsBitmapFill.as"
include "GraphicsEndFill.as"
include "GraphicsGradientFill.as"
include "GraphicsPath.as"
include "GraphicsPathCommand.as"
include "GraphicsPathWinding.as"
include "GraphicsShaderFill.as"
include "GraphicsSolidFill.as"
include "GraphicsStroke.as"
include "GraphicsTrianglePath.as"
//include "NativeMenu.as"		to DependInclude.as
include "NativeMenuItem.as"
include "NativeWindow.as"
include "NativeWindowDisplayState.as"
include "NativeWindowInitOptions.as"
include "NativeWindowResize.as"
include "NativeWindowSystemChrome.as"
include "NativeWindowType.as"
include "Screen.as"
include "Shader.as"
include "ShaderData.as"
include "ShaderInput.as"
include "ShaderJob.as"
include "ShaderParameter.as"
include "ShaderParameterType.as"
include "ShaderPrecision.as"
include "StageAspectRatio.as"
include "StageOrientation.as"
include "TriangleCulling.as"
include "IBitmapDrawable.as"
include "BitmapData.as"	
include "NativeMenu.as"
include	"InteractiveObject.as"	
include "Graphics.as"	
include "Scene.as"
include "ActionScriptVersion.as"
include "BitmapDataChannel.as"
include "BlendMode.as"
include "CapsStyle.as"
include "FrameLabel.as"
include "GradientType.as"
include "InterpolationMethod.as"
include "JointStyle.as"
include "LineScaleMode.as"
include "PixelSnapping.as"
include "SWFVersion.as"
include "StageScaleMode.as"
include "StageAlign.as"
include "StageDisplayState.as"
include "StageQuality.as"
include "SpreadMethod.as"
include	"AVM1Movie.as"
include	"Bitmap.as"
include	"DisplayObjectContainer.as"	
include	"Sprite.as"
include	"MovieClip.as"
include	"Stage.as"
include	"SimpleButton.as"	
include	"MorphShape.as"	
include	"Shape.as"
include	"LoaderInfo.as"	
include	"BitmapEncodingColorSpace.as"
include	"JPEGEncoderOptions.as"
include	"JPEGXREncoderOptions.as"
include	"NativeWindowRenderMode.as"
include	"PNGEncoderOptions.as"
include	"Stage3D.as"

